### ISSUE TITLE
ESP8266 WiFi support

### ISSUE THREAD

**Issue by oori** [goddland16/Modbus-TCP#1]
What are the prospects of integrating your library with [ESP8266WiFi](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi)  (part of the [ESP8266 core](https://github.com/esp8266/Arduino))?

Seems like your library is the only with tcp modbus master capabilities...  Thanks.

**Comment by goddland16** [comment]
Yes, certainly you can. That would be great. Since I am new, please tell me what to do. And I won't be available since I am busy currently. Thanks.

**Comment by flouk19** [comment]
I extended the library by the esp8266WiFi module, feel free to use

**Comment by oori** [comment]
@flouk19 Thanks!  it works.  
I suggest you add an example file, and push a PR to @goddland16

**Comment by flouk19** [comment]
@oori I am unable to make an example file till next week Monday or Tuesday, but then I am going to make one

**Comment by flouk19** [comment]
I guess this issue can be closed, as the pull request is merged
